# -*- coding: utf-8 -*-
"""Cancer Project part_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hjQArTwZBnWDvxWzTmHBs0Os-1dKE9Og
"""

import copy, math
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import csv
from pathlib import Path

# Lista dei nomi dei file TSV da leggere
file_names = ['msk_met_2021_clinical_data.tsv']

# Leggi ciascun file e crea una lista di DataFrame
dfs = [pd.read_csv(file, sep='\t') for file in file_names]

# Combina i DataFrame in un unico DataFrame utilizzando pd.concat
df_pan = pd.concat(dfs, ignore_index=True)

# Stampa il DataFrame risultante
print(df_pan)

df_pan.head()

"""# Nuova sezione"""

df2 = df_pan[df_pan.columns[3:]]
df2.head()

df3 = df2.iloc[:, list(range(0, 44)) + list(range(45, 52))]
df3.head()

df3['Time'] = df3['Age at Death'] - df3['Age at First Mets Dx']
df3.head()

df3[:] = df3[:].replace({'No': 0, 'Yes': 1})
df3.head()

df3['1st Mets'] = df3['Age at Last Contact'] - df3['Age at First Mets Dx']
df3.head()

df3['Time between Discovery and Procedure'] = df3['Age at Surgical Procedure'] - df3['Age at First Mets Dx'] #quelli negativi si sono operati solo al Tumore, NON alla metastasi

df4 = df3.iloc[:, list(range(0, 47)) + list(range(49, 54))]
df4 = df4.iloc[:, list(range(0, 6)) + list(range(7, 52))]

!pip install inflect

import pandas as pd
import inflect
import numpy as np

# Unire le colonne usando combine_first
df4['Age at Last Contact'] = df4['Age at Death'].combine_first(df4['Age at Last Contact'])
a=float(4.90)
# Definire la funzione per assegnare il range
def assegna_range(numero):
    return f"{((numero // 5) * 5)}-{((numero // 5) * 5) + a}"

# Applicare la funzione alla colonna
df4['Age at Death Range'] = df4['Age at Death'].apply(assegna_range)
df4['Age at First Mets Dx Range'] = df4['Age at First Mets Dx'].apply(assegna_range)
df4['Age at Last Contact Range'] = df4['Age at Last Contact'].apply(assegna_range)
df4['Age at Sequencing Range'] = df4['Age at Sequencing'].apply(assegna_range)
df4['Age at Surgical Procedure Range'] = df4['Age at Surgical Procedure'].apply(assegna_range)

# Stampare il dataframe risultante
# Stampare il dataframe risultante
df4 = df4.iloc[:, list(range(5, 56))]

df4 = df4.dropna(subset=['Mutation Count'])
df4 = df4.dropna(subset=['Tumor Purity'])
df4 = df4.dropna(subset=['MSI Score'])
df4[:] = df4[:].replace({'nan-nan': 'No'})
df4['Metastatic Site'].fillna('Unspecified', inplace=True)
df4['Age at Surgical Procedure Range'].fillna('No', inplace=True)
df4 = df4.drop('Age at Death Range', axis=1)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

df4 = df4.drop('Oncotree Code', axis=1)
df4 = df4.drop('Time', axis=1)
df4 = df4.drop('1st Mets', axis=1)
df4 = df4.drop('Time between Discovery and Procedure', axis=1)

df4.head(28)

df4[:] = df4[:].replace({'Uvula': 'Oral Cavity'})
df4[:] = df4[:].replace({'Uvea': 'Eye'})
df4[:] = df4[:].replace({'Uterus, Ovaries': 'Uterus'})
df4[:] = df4[:].replace({'Soft Palate': 'Oral Cavity'})
df4[:] = df4[:].replace({'Tibia': 'Bone'})
df4[:] = df4[:].replace({'Spine': 'Bone'})
df4[:] = df4[:].replace({'Skin Ear': 'Skin'})
df4[:] = df4[:].replace({'Scapula': 'Bone'})
df4[:] = df4[:].replace({'Sacral Mass': 'Bone'})
df4[:] = df4[:].replace({'Right Forearm': 'Bone'})
df4[:] = df4[:].replace({'Retroperitenium': 'Retroperitoneum'})
df4[:] = df4[:].replace({'Prostatic urethra': 'Ureter'})
df4[:] = df4[:].replace({'Perineal': 'Skin'})
df4[:] = df4[:].replace({'Pelvic Nodule': 'Pelvis'})
df4[:] = df4[:].replace({'Pelvic mass': 'Pelvis'})
df4[:] = df4[:].replace({'Paraspinal': 'Bone'})
df4[:] = df4[:].replace({'Orbit - Right': 'Eye'})
df4[:] = df4[:].replace({'Omentum': 'Peritoneum'})
df4[:] = df4[:].replace({'Nasal Moscher Biopsy': 'Nose'})
df4[:] = df4[:].replace({'Nasal Cavity': 'Nose'})
df4[:] = df4[:].replace({'Melanoma of Unknown Primary': 'Cancer of Unknown Primary'})
df4[:] = df4[:].replace({'Left Thigh': 'Bone'})
df4[:] = df4[:].replace({'left ovary and fallopian tube': 'Ovary'})
df4[:] = df4[:].replace({'Left Colon': 'Colon'})
df4[:] = df4[:].replace({'Lacrimal Gland': 'Eye'})
df4[:] = df4[:].replace({'Knee': 'Bone'})
df4[:] = df4[:].replace({'Intrahepatic Bile Duct': 'Liver'})
df4[:] = df4[:].replace({'Inguinal Canal': 'Pelvis'})
df4[:] = df4[:].replace({'Heart - Right Ventricle': 'Heart'})
df4[:] = df4[:].replace({'Head and Neck': 'Bone'})
df4[:] = df4[:].replace({'Hard palate': 'Bone'})
df4[:] = df4[:].replace({'Groin': 'Pelvis'})
df4[:] = df4[:].replace({'Glabella': 'Skin'})
df4[:] = df4[:].replace({'Gingiva': 'Oral Cavity'})
df4[:] = df4[:].replace({'Ethmoid Sinus': 'Nose'})
df4[:] = df4[:].replace({'Epiglottis': 'Oral Cavity'})
df4[:] = df4[:].replace({'Endome': 'Endometrium'})
df4[:] = df4[:].replace({'Ectopic Embryonic Rest': 'Uterus'})
df4[:] = df4[:].replace({'Ear Canal': 'Bone'})
df4[:] = df4[:].replace({'distal bile duct': 'Liver'})
df4[:] = df4[:].replace({'common Bile Duct': 'Liver'})
df4[:] = df4[:].replace({'Cheek': 'Mouth'})
df4[:] = df4[:].replace({'Carcinoma of Unknown Primary': 'Cancer of Unknown Primary'})
df4[:] = df4[:].replace({'Buccal Mucosa': 'Oral Cavity'})
df4[:] = df4[:].replace({'Buccal': 'Oral Cavity'})
df4[:] = df4[:].replace({'Blood Vessel': 'Heart'})
df4[:] = df4[:].replace({'Biliary Tract': 'Liver'})
df4[:] = df4[:].replace({'Auditory Canal': 'Bone'})
df4[:] = df4[:].replace({'Anorectal Junction': 'Anus'})
df4[:] = df4[:].replace({'Adrenal': 'Kidney'})
df4[:] = df4[:].replace({'Adnexa': 'Skin'})
df4[:] = df4[:].replace({'Upper Back': 'Bone'})
df4[:] = df4[:].replace({'Thigh - Left': 'Bone'})
df4[:] = df4[:].replace({'Skull Base - Pterygoid margin': 'Bone'})
df4[:] = df4[:].replace({'shoulder': 'Bone'})
df4[:] = df4[:].replace({'Rectal Mucosa': 'Anus'})
df4[:] = df4[:].replace({'Orbital Floor': 'Eye'})
df4[:] = df4[:].replace({'Lymph Node': 'Skin'})
df4[:] = df4[:].replace({'Left parietal Pleura': 'Pleura'})
df4[:] = df4[:].replace({'Ileocecal Valve': 'Ileum'})
df4[:] = df4[:].replace({'Hip': 'Bone'})
df4[:] = df4[:].replace({'Forearm': 'Bone'})
df4[:] = df4[:].replace({'Duodenum-Jejunum': 'Duodenum'})
df4[:] = df4[:].replace({'Adrenal Gland': 'Kidney'})
df4[:] = df4[:].replace({'Unknown Primary': 'Cancer of Unknown Primary'})
df4[:] = df4[:].replace({'Right Foot': 'Bone'})
df4[:] = df4[:].replace({'Rectum and Colon': 'Colon'})
df4[:] = df4[:].replace({'Pleural Fluid': 'Pleura'})
df4[:] = df4[:].replace({'Hypopharynx vs Oropharynx': 'Oral Cavity'})
df4[:] = df4[:].replace({'Esophagus/Stomach': 'Stomach'})
df4[:] = df4[:].replace({'Scrotum': 'Testis'})
df4[:] = df4[:].replace({'Muscle': 'Bone'})
df4[:] = df4[:].replace({'Gastric Wall': 'Stomach'})
df4[:] = df4[:].replace({'Flank': 'Bone'})
df4[:] = df4[:].replace({'base of tongue': 'Oral Cavity'})
df4[:] = df4[:].replace({'Upper Extremity': 'Bone'})
df4[:] = df4[:].replace({'Trigone': 'Ureter'})
df4[:] = df4[:].replace({'Sinonasal': 'Nose'})

df4[:] = df4[:].replace({'Skin, Ear': 'Skin'})
df4[:] = df4[:].replace({'Shoulder': 'Bone'})
df4[:] = df4[:].replace({'Left Parietal Pleura': 'Pleura'})
df4[:] = df4[:].replace({'Mediastinum': 'Bone'})
df4[:] = df4[:].replace({'Base of Tongue': 'Oral Cavity'})
df4[:] = df4[:].replace({'Mesentery': 'Pelvis'})
df4[:] = df4[:].replace({'Diaphragm': 'Lung'})
df4[:] = df4[:].replace({'Abdominal Wall': 'Abdomen'})
df4[:] = df4[:].replace({'Peritoneum': 'Colon'})
df4[:] = df4[:].replace({'Hepatic flexure': 'Liver'})
df4[:] = df4[:].replace({'Buttock': 'Skin'})
df4[:] = df4[:].replace({'Uterus/Cervix': 'Uterus'})
df4[:] = df4[:].replace({'Trachea': 'Lung'})
df4[:] = df4[:].replace({'Maxillary Sinus': 'Nose'})
df4[:] = df4[:].replace({'Hypopharynx': 'Oral Cavity'})
df4[:] = df4[:].replace({'Adnexa or Endometrium': 'Uterus'})
df4[:] = df4[:].replace({'Urethra': 'Ureter'})
df4[:] = df4[:].replace({'Parotid Gland': 'Oral Cavity'})
df4[:] = df4[:].replace({'Uterine': 'Uterus'})
df4[:] = df4[:].replace({'Sinus': 'Nose'})
df4[:] = df4[:].replace({'Pharynx': 'Oral Cavity'})
df4[:] = df4[:].replace({'Palate': 'Oral Cavity'})
df4[:] = df4[:].replace({'Eyelid': 'Skin'})
df4[:] = df4[:].replace({'Back': 'Bone'})
df4[:] = df4[:].replace({'Intraabdominal': 'Abdomen'})
df4[:] = df4[:].replace({'Bowel': 'Intestine'})
df4[:] = df4[:].replace({'Submandibular Gland': 'Oral Cavity'})
df4[:] = df4[:].replace({'Arm': 'Bone'})
df4[:] = df4[:].replace({'Maxilla': 'Bone'})
df4[:] = df4[:].replace({'Lower Extremity': 'Bone'})
df4[:] = df4[:].replace({'Jejunum': 'Intestine'})
df4[:] = df4[:].replace({'Gastric': 'Stomach'})
df4[:] = df4[:].replace({'Conjunctiva': 'Eye'})
df4[:] = df4[:].replace({'Small Intestine': 'Intestine'})
df4[:] = df4[:].replace({'Parotid': 'Oral Cavity'})
df4[:] = df4[:].replace({'Mouth': 'Oral Cavity'})
df4[:] = df4[:].replace({'Minor Salivary Gland': 'Oral Cavity'})
df4[:] = df4[:].replace({'Gastroesophageal': 'Stomach'})
df4[:] = df4[:].replace({'Chest Wall': 'Bone'})
df4[:] = df4[:].replace({'Leg': 'Bone'})
df4[:] = df4[:].replace({'Thigh': 'Bone'})
df4[:] = df4[:].replace({'Adnexa or Endomterium': 'Uterus'})
df4[:] = df4[:].replace({'Neck': 'Bone'})
df4[:] = df4[:].replace({'Scalp': 'Bone'})
df4[:] = df4[:].replace({'Major Salivary Gland': 'Oral Cavity'})
df4[:] = df4[:].replace({'Esophagogastric Junction': 'Stomach'})
df4[:] = df4[:].replace({'Vagina': 'Uterus'})
df4[:] = df4[:].replace({'Ileum': 'Intestine'})
df4[:] = df4[:].replace({'Vulva': 'Uterus'})
df4[:] = df4[:].replace({'Nasopharynx': 'Nose'})
df4[:] = df4[:].replace({'Salivary Gland': 'Oral Cavity'})
df4[:] = df4[:].replace({'Renal Pelvis': 'Pelvis'})
df4[:] = df4[:].replace({'Tonsil': 'Oral Cavity'})
df4[:] = df4[:].replace({'Larynx': 'Oral Cavity'})
df4[:] = df4[:].replace({'Oropharynx': 'Oral Cavity'})
df4[:] = df4[:].replace({'Kidney/Upper Tract': 'Kidney'})
df4[:] = df4[:].replace({'Duodenum': 'Intestine'})
df4[:] = df4[:].replace({'Gastroesophageal Junction': 'Stomach'})
df4[:] = df4[:].replace({'Cancer of Unknown Primary': 'Unknown'})
df4[:] = df4[:].replace({'GE Junction': 'Stomach'})
df4[:] = df4[:].replace({'Upper Tract': 'Kidney'})
df4[:] = df4[:].replace({'Retroperitoneum': 'Colon'})
df4[:] = df4[:].replace({'Tongue': 'Oral Cavity'})
df4[:] = df4[:].replace({'Cervix': 'Uterus'})
df4[:] = df4[:].replace({'Descending Colon': 'Colon'})
df4[:] = df4[:].replace({'Transverse Colon': 'Colon'})
df4[:] = df4[:].replace({'Bile Duct': 'Liver'})
df4[:] = df4[:].replace({'Small Bowel': 'Intestine'})
df4[:] = df4[:].replace({'Gallbladder': 'Liver'})
df4[:] = df4[:].replace({'Pleura': 'Lung'})
df4[:] = df4[:].replace({'Appendix': 'Intestine'})
df4[:] = df4[:].replace({'Rectosigmoid Colon': 'Colon'})
df4[:] = df4[:].replace({'Endometrium': 'Uterus'})
df4[:] = df4[:].replace({'Ascending Colon': 'Colon'})
df4[:] = df4[:].replace({'Sigmoid Colon': 'Colon'})

df4 = df4.dropna(subset=['Primary Tumor Site'])

df4[:] = df4[:].replace({'descending colon': 'Colon'})
df4[:] = df4[:].replace({'Kidney/Upper tract': 'Kidney'})
df4[:] = df4[:].replace({'Hepatic Flexure': 'Liver'})
df4[:] = df4[:].replace({'Ascending colon': 'Colon'})
df4[:] = df4[:].replace({'Transverse colon': 'Colon'})
df4[:] = df4[:].replace({'Bile duct': 'Intestine'})
df4[:] = df4[:].replace({'Base of tongue': 'Oral Cavity'})
df4[:] = df4[:].replace({'Sigmoid colon': 'Colon'})
df4[:] = df4[:].replace({'Bladder': 'Ureter'})
df4[:] = df4[:].replace({'Ovary': 'Uterus'})
df4[:] = df4[:].replace({'Esophagus': 'Oral Cavity'})
df4[:] = df4[:].replace({'Cecum': 'Intestine'})
df4[:] = df4[:].replace({'Anus': 'Intestine'})
df4[:] = df4[:].replace({'Rectum': 'Intestine'})
df4[:] = df4[:].replace({'Pelvis': 'Abdomen'})

df4[:] = df4[:].replace({'uterus': 'Uterus'})
df4 = df4.drop(df4[df4['Age at First Mets Dx Range'] == '10.0-14.9'].index)

print(df4.dtypes)

df4.describe()
df4.describe(include=object)

!pip install matplotlib

!pip install ipympl

df4 = df4.drop('FGA', axis=1)

df4['Overall Survival Status'] = df4['Overall Survival Status'].replace({'1:DECEASED': 1, '0:LIVING': 0})
df4['Race Category'].fillna('Unknown', inplace=True)
df4['Sex'].fillna('Female', inplace=True)

df4.head(28)

df4.to_excel('CancerClean4.xlsx', index=False)